### ISSUE TITLE
jquery.caret.map giving a 404

### ISSUE THREAD

**Issue by charlie-ablett** [ichord/jquery-atwho-rails#12]
jquery.caret.map
/assets/jquery.atwho

I set up the rails gem just as you said, and getting this 404.

http://localhost:3000/assets/jquery.atwho/jquery.caret.map is the URL giving the problem. Can you advise please?

Using on an older project, rails 3.1

**Comment by hailiangwangutd** [comment]
No route matches [GET] "/assets/jquery.caret.map
