### ISSUE TITLE
Username does not have link to his/her profile.

### ISSUE THREAD

**Issue by xexiu** [ichord/jquery-atwho-rails#15]
Hi,

Nice gem btw. I had managed to make it work on rails 4.1.8 on ruby 2.1.4, but doesn't seem to add a link to the specific username. It just a plain text. ```@username```. I expect to get or make something like ```<%= link to @user, @username %>```, is that posible?
Let me know about it.

**Comment by ichord** [comment]
if you are using `contentEditable` element, it is possible; otherwise, it is not.
There is a `insertTpl` option could help to archive what you expect to.
This gem is a wrapper of https://ichord.github.com/At.js ; you can checkout more in the wiki of that project.
