### ISSUE TITLE
tests failing with rails 5.2

### ISSUE THREAD

**Issue by pravi** [ichord/jquery-atwho-rails#29]
Originally reported here (has details) https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918611

**Comment by ichord** [comment]
It's because the rails app didn't use the assets pipeline, but the rails should enable the assets pipeline by default.

Did you change the default stack or use the api mode to run tests?
A similar issue: https://github.com/fgrehm/letter_opener_web/issues/46#issuecomment-273975173

**Comment by pravi** [comment]
This is how I run the tests https://salsa.debian.org/ruby-team/ruby-jquery-atwho-rails/blob/master/debian/ruby-tests.rake and it was working with rails 4, but started failing with rails 5.2.

This patch makes the tests to pass, sprockets-rails should be added as a development dependency.

```
--- a/spec/spec_helper.rb
+++ b/spec/spec_helper.rb
@@ -2,6 +2,7 @@
 require 'rails'
 require 'rails/all'
 require 'rails/generators'
+require 'sprockets/railtie'
 
 class TestApp < Rails::Application
   config.root = File.dirname(__FILE__)

```

**Comment by ichord** [comment]
```ruby
require 'rails/all'
```
https://github.com/rails/rails/blob/5-2-stable/railties/lib/rails/all.rb

Did `require 'sprockets/railtie'`

**Comment by pravi** [comment]
@ichord I don't have much idea about rails or ruby (I only manage with basic understanding of ruby to maintain debian packages). So not sure why rails/all is not enough. May be about order of requires?

**Comment by ichord** [comment]
Maybe `rails/all` raised a `LoadError` before require 'sprockets/railties', not so sure.
I saw you fix the bug and close the report, so that i will close this issue. 

I think the better way to import javascript, even for rails, is using packing toolings such as webpacker.
